# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.Dockerfile
  
tasks:
  - init: | 
      echo 'maven build'
      mvn -f projects/memapOpcServer/pom.xml clean compile install -Dmaven.test.skip=true 
      mvn -f core/cim15/pom.xml clean compile install -Dmaven.test.skip=true 
      mvn -f core/powerflow/pom.xml clean compile install -Dmaven.test.skip=true 
      mvn -f core/gridarchitect/pom.xml clean compile install -Dmaven.test.skip=true
      mvn -f projects/memapCore/pom.xml clean compile install -Dmaven.test.skip=true
      mvn -f projects/memapGui/pom.xml clean compile install -Dmaven.test.skip=true
      mkdir artifacts
      cp projects/memapGui/target/*jar-with-dependencies.jar artifacts/memapPlanungsTool.jar
      cp projects/memapCore/target/*jar-with-dependencies.jar artifacts/memapServer.jar
      cp projects/memapCore/src/main/resources/libs/lpsolve55.dll artifacts/lpsolve55.dll
      cp projects/memapCore/src/main/resources/libs/lpsolve55j.dll artifacts/lpsolve55j.dll
    command: |
      echo ' > starting MEMAP simulation environment'
      java -jar artifacts/memapServer.jar jetty 5 15
      
  - init: echo 'Onboarding of Buildings'
    command: |
      gp await-port 8013
      gp await-port 4851
      gp await-port 4852
      java -cp artifacts/memapServer.jar memap.websocket.TwoBuildingExample
      
  - init: |
      echo 'Starting MockUp EMS-Server 1'
      /home/gitpod/.pyenv/versions/3.8.12/bin/python -m pip install --upgrade pip
      python3 -m pip install opcua numpy scipy matplotlib
    command: |
      cd OPC-UA-MockupBuildings/CoSES/02_Interface_Server/House1/
      python3 CoSES_Server_Haus1.py
  - init: | 
      echo 'Starting MockUp EMS-Server 2'
      gp await-port 4851
    command: |
      cd OPC-UA-MockupBuildings/CoSES/02_Interface_Server/House2/
      python3 CoSES_Server_Haus2.py


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8013
    onOpen: notify
  - port: 7013
    onOpen: ignore
  - port: 3000
    onOpen: ignore
  - port: 4851
    onOpen: ignore
  - port: 4852
    onOpen: ignore
