# gitPod Configuration to start all Memap Services

#image:
#  file: .gitpod.Dockerfile
  
tasks:
  - name: Start MEMAP-Server
    init: echo 'starting MEMAP simulation environment'
    command: java /projects/memapCore/scr/main/java/main/memap/Simulation.java jetty 5 15
    openMode: split-right
    
 # - name: Start PostGreSQL
 #   command: pg_start
    
  - name: Start Mock-Up 1
    init: echo 'Starting Mock-Up Bulding 1 with EMS-Server, using the MEMAP OPC UA data model'
    command: python /projects/memapCore/scr/main/java/main/memap/Simulation.java jetty 5 15
  - name: Start Mock-Up 2
    init: echo 'Starting Mock-Up Bulding 2 with EMS-Server, using the MEMAP OPC UA data model'
    command: python /projects/memapCore/scr/main/java/main/memap/Simulation.java jetty 5 15
  - name: Testing Building Servers
    command: |
      gp await-port 4851
      echo 'Port 4851 ( Building 1 is now availible)'
      gp await-port 4852
      echo 'Port 4852 ( Building 2 is now availible)'
      
   - name: Start MEMAP
    init: echo 'Onboarding of local EMS and start of simulation'
    command: java /projects/memapCore/scr/main/java/main/memap/websocket/TwoBuildingExample.java

# List the ports to expose.
ports:
  - port: 8013
    onOpen: notify
  - port: 7013
    onOpen: igore
  - port: 3000
    onOpen: ignore
  - port: 4851
    onOpen: ignore
  - port: 4852
    onOpen: ignore
    

