{
 "title": "CoSES_Data",
 "time": { "from": "2021-01-30T21:10:00.000Z", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CO2 Emissionen Gesamt",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  totalco2emissions\nFROM memap\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Strompreis",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  electricityprice_eur\nFROM memap\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "MEMAP - Nachfrage Wärme und empfohlene Produktion / Zukauf",
   "type": "graph",
   "description": "Lastprofil aus Riemerling skaliert",
   "gridPos": { "h": 14, "w": 9, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Leistung (kW)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  memap_systemheatdemand AS \"Nachfrage\",\n  memap_ls01ems01obj01_coupl01 AS \"Wärmepumpe\",\n  memap_ls01ems02obj01_coupl01 AS \"BHKW\",\n  memap_ls01ems02obj01_vprod01 AS \"Solarthermie\"\nFROM memap\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "MEMAP - Nachfrage Strom und empfohlene Produktion / Zukauf",
   "type": "graph",
   "description": "Lastprofil aus Riemerling skaliert",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Leistung (kW)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  memap_systemelectricitydemand AS \"Nachfrage\",\n  memap_ls01ems01obj01_vprod01 AS \"PV-Produkltion\",\n  memap_elecbuy AS \"Strom Einkauf\",\n  memap_elecsell AS \"Strom Verkauf\"\nFROM memap\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "abgeschlatete Zeitschritte",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  sum(memap_ls01ems01obj01_coupl01off) OVER (ORDER BY \"timestamp\") AS \"Wärmepumpe Off-time\",\n  sum(memap_ls01ems02obj01_coupl01off) OVER (ORDER BY \"timestamp\") AS \"BHKW Off-time\"\nFROM memap\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Kosten letzter Zeitschritt ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  sum(memap_elecbuy) OVER (ORDER BY \"timestamp\") AS \"Strom Einkauf (total)\",\n  sum(memap_elecsell) OVER (ORDER BY \"timestamp\") AS \"Strom Verkauf (total)\"\nFROM memap\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Kummulierte MEMAP-Kosten (pro Simulationsrun)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "currencyEUR", "label": "kummulierte Kosten" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  totalcostseur AS \"kummulierte Kosten\"\nFROM memap\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Ent- / Ladevorgänge Speicher",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "Ent-/Ladeleistung [kW]" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  memap_ls01ems01obj01_strge01charge-memap_ls01ems01obj01_strge01discharge AS \"Batterie\",\n  memap_ls01ems02obj01_strge01charge-memap_ls01ems02obj01_strge01discharge AS \"Wärmespeicher\"\nFROM memap\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "State of Charge (SOC) des Speichers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 14 },
   "yaxes": [
    { "format": "percentunit", "label": "Ladestand" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  memap_ls01ems01obj01_strge01_soc AS \"SOC Batterie\",\n  memap_ls01ems02obj01_strge01_soc AS \"SOC Wärmespeicher\"\nFROM memap\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  }
 ]
}