{
 "title": "CoSES_Data",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CO2 Emissionen Gesamt",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  totalco2emissions\nFROM building1memapon\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  totalco2emissions\nFROM building2memapon\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Strompreis",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  electricityprice_eur\nFROM building1memapon\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "MEMAP - Nachfrage Wärme und empfohlene Produktion / Zukauf",
   "type": "graph",
   "description": "Lastprofil aus Riemerling skaliert",
   "gridPos": { "h": 14, "w": 9, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  b1_systemheatdemand AS \"Nachfrage\",\n  b1_ls01ems01obj01_coupl01 AS \"LS01_COUPL\",\n  b1_ls02ems02obj01_coupl01 AS \"LS02_COUPL\"\nFROM building1memapon\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "MEMAP - Nachfrage Strom und empfohlene Produktion / Zukauf",
   "type": "graph",
   "description": "Lastprofil aus Riemerling skaliert",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  b1_systemelectricitydemand AS \"Nachfrage\",\n  b1_ls01ems01obj01_vprod01 AS \"VProd01\",\n  b1_elecbuy AS \"Strom Einkauf\"\nFROM building1memapon\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Kosten letzter Zeitschritt ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  b1_elecbuy AS \"Strom einkauf\",\n  b1_elecsell AS \"Strom Verkauf\"\nFROM building1memapon\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "kummulierte MEMAP-Kosten (pro Simulationsrun(",
   "type": "graph",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "currencyEUR", "label": "Kosten" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  totalcostseur AS \"kummulierte Kosten\"\nFROM building1memapon\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Ent- / Ladevorgänge Speicher",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  b1_ls01ems01obj01_strge01charge AS \"LS01 Stor01 laden\",\n  b1_ls01ems01obj01_strge01discharge AS \"LS01 Stor01 entladen\",\n  b1_ls02ems02obj01_strge01charge AS \"LS02 Stor01 laden\",\n  b1_ls02ems02obj01_strge01discharge AS \"LS02 Stor01 entladen\"\nFROM building1memapon\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "State of Charge (SOC) des Speichers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 15, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  b1_ls02ems02obj01_strge01_soc AS \"SOC Strge-Building one\",\n  b1_ls01ems01obj01_strge01_soc AS \"SOC Strge-Building two\"\nFROM building1memapon\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "abgeschlatete Zeitschritte",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  sum(b1_ls01ems01obj01_coupl01off) OVER (ORDER BY \"timestamp\") AS \"LS01 Coupl Off-time\",\n  sum(b1_ls02ems02obj01_coupl01off) OVER (ORDER BY \"timestamp\") AS \"LS02 Coupl Off-time\"\nFROM building1memapon\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  }
 ]
}