//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.07 at 04:15:46 PM CEST 
//


package opcMEMAP.serverConfigurationClassesXML;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="userTokenPolicies" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="applicationUri" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nameSpaces">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="nameSpace" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="folderNodes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="folderNode" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="nodeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="nameSpace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="displayName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="nodes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="node" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="datatype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="displayName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="nodeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="nameSpace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="parentFolder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="accessLevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="userAccessLevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="minSamplingInterval" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;element name="historizing" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="dataSourceConnector" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="modbusConnector">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="protocolType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="slaveAddress" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="ipAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="modbusPort" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="baudRate" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="dataBits" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="stopBits" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="parity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="operation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="samplingInterval" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="registerAddress" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="registerLength" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="dataType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="mqttConnector">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="mqttHost" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="topic" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="operation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="samplingInterval" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="dataType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "host",
    "port",
    "userTokenPolicies",
    "username",
    "password",
    "applicationUri",
    "nameSpaces",
    "folderNodes",
    "nodes"
})
@XmlRootElement(name = "serverconfig")
@Deprecated
public class ServerConfig {

    @XmlElement(required = true)
    protected String host;
    protected int port;
    @XmlElement(required = true)
    protected String userTokenPolicies;
    @XmlElement(required = true)
    protected String username;
    @XmlElement(required = true)
    protected String password;
    @XmlElement(required = true)
    protected String applicationUri;
    @XmlElement(required = true)
    protected ServerConfig.NameSpaces nameSpaces;
    @XmlElement(required = true)
    protected ServerConfig.FolderNodes folderNodes;
    @XmlElement(required = true)
    protected ServerConfig.Nodes nodes;

    /**
     * Gets the value of the host property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHost() {
        return host;
    }

    /**
     * Sets the value of the host property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHost(String value) {
        this.host = value;
    }

    /**
     * Gets the value of the port property.
     * 
     */
    public int getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     */
    public void setPort(int value) {
        this.port = value;
    }

    /**
     * Gets the value of the userTokenPolicies property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserTokenPolicies() {
        return userTokenPolicies;
    }

    /**
     * Sets the value of the userTokenPolicies property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserTokenPolicies(String value) {
        this.userTokenPolicies = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the applicationUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationUri() {
        return applicationUri;
    }

    /**
     * Sets the value of the applicationUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationUri(String value) {
        this.applicationUri = value;
    }

    /**
     * Gets the value of the nameSpaces property.
     * 
     * @return
     *     possible object is
     *     {@link ServerConfig.NameSpaces }
     *     
     */
    public ServerConfig.NameSpaces getNameSpaces() {
        return nameSpaces;
    }

    /**
     * Sets the value of the nameSpaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerConfig.NameSpaces }
     *     
     */
    public void setNameSpaces(ServerConfig.NameSpaces value) {
        this.nameSpaces = value;
    }

    /**
     * Gets the value of the folderNodes property.
     * 
     * @return
     *     possible object is
     *     {@link ServerConfig.FolderNodes }
     *     
     */
    public ServerConfig.FolderNodes getFolderNodes() {
        return folderNodes;
    }

    /**
     * Sets the value of the folderNodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerConfig.FolderNodes }
     *     
     */
    public void setFolderNodes(ServerConfig.FolderNodes value) {
        this.folderNodes = value;
    }

    /**
     * Gets the value of the nodes property.
     * 
     * @return
     *     possible object is
     *     {@link ServerConfig.Nodes }
     *     
     */
    public ServerConfig.Nodes getNodes() {
        return nodes;
    }

    /**
     * Sets the value of the nodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerConfig.Nodes }
     *     
     */
    public void setNodes(ServerConfig.Nodes value) {
        this.nodes = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="folderNode" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="nodeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="nameSpace" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="displayName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "folderNode"
    })
    public static class FolderNodes {

        @XmlElement(required = true)
        protected List<ServerConfig.FolderNodes.FolderNode> folderNode;

        /**
         * Gets the value of the folderNode property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the folderNode property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFolderNode().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ServerConfig.FolderNodes.FolderNode }
         * 
         * 
         */
        public List<ServerConfig.FolderNodes.FolderNode> getFolderNode() {
            if (folderNode == null) {
                folderNode = new ArrayList<ServerConfig.FolderNodes.FolderNode>();
            }
            return this.folderNode;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="nodeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="nameSpace" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="displayName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nodeId",
            "nameSpace",
            "displayName",
            "description"
        })
        public static class FolderNode {

            @XmlElement(required = true)
            protected String nodeId;
            @XmlElement(required = true)
            protected String nameSpace;
            @XmlElement(required = true)
            protected String displayName;
            @XmlElement(required = true)
            protected String description;

            /**
             * Gets the value of the nodeId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNodeId() {
                return nodeId;
            }

            /**
             * Sets the value of the nodeId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNodeId(String value) {
                this.nodeId = value;
            }

            /**
             * Gets the value of the nameSpace property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNameSpace() {
                return nameSpace;
            }

            /**
             * Sets the value of the nameSpace property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNameSpace(String value) {
                this.nameSpace = value;
            }

            /**
             * Gets the value of the displayName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDisplayName() {
                return displayName;
            }

            /**
             * Sets the value of the displayName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDisplayName(String value) {
                this.displayName = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }
            //not an autogenerated method
            public String toString() {  
            	return nodeId;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="nameSpace" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nameSpace"
    })
    public static class NameSpaces {

        @XmlElement(required = true)
        protected List<String> nameSpace;

        /**
         * Gets the value of the nameSpace property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the nameSpace property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNameSpace().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getNameSpace() {
            if (nameSpace == null) {
                nameSpace = new ArrayList<String>();
            }
            return this.nameSpace;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="node" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="datatype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="displayName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="nodeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="nameSpace" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="parentFolder" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="accessLevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="userAccessLevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="minSamplingInterval" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                   &lt;element name="historizing" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="dataSourceConnector" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="modbusConnector">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="protocolType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="slaveAddress" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="ipAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="modbusPort" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="baudRate" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="dataBits" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="stopBits" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="parity" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="operation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="samplingInterval" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="registerAddress" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="registerLength" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="dataType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="mqttConnector">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="mqttHost" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="topic" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="operation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="samplingInterval" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="dataType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "node"
    })
    public static class Nodes {

        @XmlElement(required = true)
        protected List<ServerConfig.Nodes.Node> node;

        /**
         * Gets the value of the node property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the node property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNode().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ServerConfig.Nodes.Node }
         * 
         * 
         */
        public List<ServerConfig.Nodes.Node> getNode() {
            if (node == null) {
                node = new ArrayList<ServerConfig.Nodes.Node>();
            }
            return this.node;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="datatype" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="displayName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="nodeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="nameSpace" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="parentFolder" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="accessLevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="userAccessLevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="minSamplingInterval" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *         &lt;element name="historizing" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="dataSourceConnector" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="modbusConnector">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="protocolType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="slaveAddress" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="ipAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="modbusPort" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="baudRate" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="dataBits" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="stopBits" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="parity" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="operation" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="samplingInterval" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="registerAddress" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="registerLength" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="dataType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="mqttConnector">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="mqttHost" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="topic" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="operation" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="samplingInterval" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="dataType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "datatype",
            "displayName",
            "nodeId",
            "nameSpace",
            "parentFolder",
            "description",
            "value",
            "accessLevel",
            "userAccessLevel",
            "minSamplingInterval",
            "historizing",
            "dataSourceConnector",
            "modbusConnector",
            "mqttConnector"
        })
        public static class Node {

            @XmlElement(required = true)
            protected String datatype;
            @XmlElement(required = true)
            protected String displayName;
            @XmlElement(required = true)
            protected String nodeId;
            @XmlElement(required = true)
            protected String nameSpace;
            @XmlElement(required = true)
            protected String parentFolder;
            @XmlElement(required = true)
            protected String description;
            @XmlElement(required = true)
            protected String value;
            @XmlElement(required = true)
            protected String accessLevel;
            @XmlElement(required = true)
            protected String userAccessLevel;
            protected double minSamplingInterval;
            protected boolean historizing;
            @XmlElement(required = true)
            protected String dataSourceConnector;
            @XmlElement(required = true)
            protected ServerConfig.Nodes.Node.ModbusConnector modbusConnector;
            @XmlElement(required = true)
            protected ServerConfig.Nodes.Node.MqttConnector mqttConnector;

            /**
             * Gets the value of the datatype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDatatype() {
                return datatype;
            }

            /**
             * Sets the value of the datatype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDatatype(String value) {
                this.datatype = value;
            }

            /**
             * Gets the value of the displayName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDisplayName() {
                return displayName;
            }

            /**
             * Sets the value of the displayName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDisplayName(String value) {
                this.displayName = value;
            }

            /**
             * Gets the value of the nodeId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNodeId() {
                return nodeId;
            }

            /**
             * Sets the value of the nodeId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNodeId(String value) {
                this.nodeId = value;
            }

            /**
             * Gets the value of the nameSpace property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNameSpace() {
                return nameSpace;
            }

            /**
             * Sets the value of the nameSpace property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNameSpace(String value) {
                this.nameSpace = value;
            }

            /**
             * Gets the value of the parentFolder property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getParentFolder() {
                return parentFolder;
            }

            /**
             * Sets the value of the parentFolder property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setParentFolder(String value) {
                this.parentFolder = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the accessLevel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAccessLevel() {
                return accessLevel;
            }

            /**
             * Sets the value of the accessLevel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAccessLevel(String value) {
                this.accessLevel = value;
            }

            /**
             * Gets the value of the userAccessLevel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUserAccessLevel() {
                return userAccessLevel;
            }

            /**
             * Sets the value of the userAccessLevel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUserAccessLevel(String value) {
                this.userAccessLevel = value;
            }

            /**
             * Gets the value of the minSamplingInterval property.
             * 
             */
            public double getMinSamplingInterval() {
                return minSamplingInterval;
            }

            /**
             * Sets the value of the minSamplingInterval property.
             * 
             */
            public void setMinSamplingInterval(double value) {
                this.minSamplingInterval = value;
            }

            /**
             * Gets the value of the historizing property.
             * 
             */
            public boolean isHistorizing() {
                return historizing;
            }

            /**
             * Sets the value of the historizing property.
             * 
             */
            public void setHistorizing(boolean value) {
                this.historizing = value;
            }

            /**
             * Gets the value of the dataSourceConnector property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDataSourceConnector() {
                return dataSourceConnector;
            }

            /**
             * Sets the value of the dataSourceConnector property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDataSourceConnector(String value) {
                this.dataSourceConnector = value;
            }

            /**
             * Gets the value of the modbusConnector property.
             * 
             * @return
             *     possible object is
             *     {@link ServerConfig.Nodes.Node.ModbusConnector }
             *     
             */
            public ServerConfig.Nodes.Node.ModbusConnector getModbusConnector() {
                return modbusConnector;
            }

            /**
             * Sets the value of the modbusConnector property.
             * 
             * @param value
             *     allowed object is
             *     {@link ServerConfig.Nodes.Node.ModbusConnector }
             *     
             */
            public void setModbusConnector(ServerConfig.Nodes.Node.ModbusConnector value) {
                this.modbusConnector = value;
            }

            /**
             * Gets the value of the mqttConnector property.
             * 
             * @return
             *     possible object is
             *     {@link ServerConfig.Nodes.Node.MqttConnector }
             *     
             */
            public ServerConfig.Nodes.Node.MqttConnector getMqttConnector() {
                return mqttConnector;
            }

            /**
             * Sets the value of the mqttConnector property.
             * 
             * @param value
             *     allowed object is
             *     {@link ServerConfig.Nodes.Node.MqttConnector }
             *     
             */
            public void setMqttConnector(ServerConfig.Nodes.Node.MqttConnector value) {
                this.mqttConnector = value;
            }
            
            public String toString() {  
            	return nodeId;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="protocolType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="slaveAddress" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="ipAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="modbusPort" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="baudRate" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="dataBits" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="stopBits" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="parity" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="operation" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="samplingInterval" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="registerAddress" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="registerLength" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="dataType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "protocolType",
                "slaveAddress",
                "ipAddress",
                "modbusPort",
                "baudRate",
                "dataBits",
                "stopBits",
                "parity",
                "operation",
                "samplingInterval",
                "registerAddress",
                "registerLength",
                "dataType"
            })
            public static class ModbusConnector {

                @XmlElement(required = true)
                protected String protocolType;
                protected int slaveAddress;
                @XmlElement(required = true)
                protected String ipAddress;
                @XmlElement(required = true)
                protected String modbusPort;
                protected int baudRate;
                protected int dataBits;
                protected int stopBits;
                protected int parity;
                @XmlElement(required = true)
                protected String operation;
                protected int samplingInterval;
                protected int registerAddress;
                protected int registerLength;
                @XmlElement(required = true)
                protected String dataType;

                /**
                 * Gets the value of the protocolType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getProtocolType() {
                    return protocolType;
                }

                /**
                 * Sets the value of the protocolType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setProtocolType(String value) {
                    this.protocolType = value;
                }

                /**
                 * Gets the value of the slaveAddress property.
                 * 
                 */
                public int getSlaveAddress() {
                    return slaveAddress;
                }

                /**
                 * Sets the value of the slaveAddress property.
                 * 
                 */
                public void setSlaveAddress(int value) {
                    this.slaveAddress = value;
                }

                /**
                 * Gets the value of the ipAddress property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIpAddress() {
                    return ipAddress;
                }

                /**
                 * Sets the value of the ipAddress property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIpAddress(String value) {
                    this.ipAddress = value;
                }

                /**
                 * Gets the value of the modbusPort property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getModbusPort() {
                    return modbusPort;
                }

                /**
                 * Sets the value of the modbusPort property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setModbusPort(String value) {
                    this.modbusPort = value;
                }

                /**
                 * Gets the value of the baudRate property.
                 * 
                 */
                public int getBaudRate() {
                    return baudRate;
                }

                /**
                 * Sets the value of the baudRate property.
                 * 
                 */
                public void setBaudRate(int value) {
                    this.baudRate = value;
                }

                /**
                 * Gets the value of the dataBits property.
                 * 
                 */
                public int getDataBits() {
                    return dataBits;
                }

                /**
                 * Sets the value of the dataBits property.
                 * 
                 */
                public void setDataBits(int value) {
                    this.dataBits = value;
                }

                /**
                 * Gets the value of the stopBits property.
                 * 
                 */
                public int getStopBits() {
                    return stopBits;
                }

                /**
                 * Sets the value of the stopBits property.
                 * 
                 */
                public void setStopBits(int value) {
                    this.stopBits = value;
                }

                /**
                 * Gets the value of the parity property.
                 * 
                 */
                public int getParity() {
                    return parity;
                }

                /**
                 * Sets the value of the parity property.
                 * 
                 */
                public void setParity(int value) {
                    this.parity = value;
                }

                /**
                 * Gets the value of the operation property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOperation() {
                    return operation;
                }

                /**
                 * Sets the value of the operation property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOperation(String value) {
                    this.operation = value;
                }

                /**
                 * Gets the value of the samplingInterval property.
                 * 
                 */
                public int getSamplingInterval() {
                    return samplingInterval;
                }

                /**
                 * Sets the value of the samplingInterval property.
                 * 
                 */
                public void setSamplingInterval(int value) {
                    this.samplingInterval = value;
                }

                /**
                 * Gets the value of the registerAddress property.
                 * 
                 */
                public int getRegisterAddress() {
                    return registerAddress;
                }

                /**
                 * Sets the value of the registerAddress property.
                 * 
                 */
                public void setRegisterAddress(int value) {
                    this.registerAddress = value;
                }

                /**
                 * Gets the value of the registerLength property.
                 * 
                 */
                public int getRegisterLength() {
                    return registerLength;
                }

                /**
                 * Sets the value of the registerLength property.
                 * 
                 */
                public void setRegisterLength(int value) {
                    this.registerLength = value;
                }

                /**
                 * Gets the value of the dataType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDataType() {
                    return dataType;
                }

                /**
                 * Sets the value of the dataType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDataType(String value) {
                    this.dataType = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="mqttHost" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="topic" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="operation" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="samplingInterval" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="dataType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "mqttHost",
                "username",
                "password",
                "topic",
                "operation",
                "samplingInterval",
                "dataType"
            })
            public static class MqttConnector {

                @XmlElement(required = true)
                protected String mqttHost;
                @XmlElement(required = true)
                protected String username;
                @XmlElement(required = true)
                protected String password;
                @XmlElement(required = true)
                protected String topic;
                @XmlElement(required = true)
                protected String operation;
                protected int samplingInterval;
                @XmlElement(required = true)
                protected String dataType;

                /**
                 * Gets the value of the mqttHost property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMqttHost() {
                    return mqttHost;
                }

                /**
                 * Sets the value of the mqttHost property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMqttHost(String value) {
                    this.mqttHost = value;
                }

                /**
                 * Gets the value of the username property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUsername() {
                    return username;
                }

                /**
                 * Sets the value of the username property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUsername(String value) {
                    this.username = value;
                }

                /**
                 * Gets the value of the password property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPassword() {
                    return password;
                }

                /**
                 * Sets the value of the password property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPassword(String value) {
                    this.password = value;
                }

                /**
                 * Gets the value of the topic property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTopic() {
                    return topic;
                }

                /**
                 * Sets the value of the topic property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTopic(String value) {
                    this.topic = value;
                }

                /**
                 * Gets the value of the operation property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOperation() {
                    return operation;
                }

                /**
                 * Sets the value of the operation property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOperation(String value) {
                    this.operation = value;
                }

                /**
                 * Gets the value of the samplingInterval property.
                 * 
                 */
                public int getSamplingInterval() {
                    return samplingInterval;
                }

                /**
                 * Sets the value of the samplingInterval property.
                 * 
                 */
                public void setSamplingInterval(int value) {
                    this.samplingInterval = value;
                }

                /**
                 * Gets the value of the dataType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDataType() {
                    return dataType;
                }

                /**
                 * Sets the value of the dataType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDataType(String value) {
                    this.dataType = value;
                }

            }

        }

    }

}
