# This workflow builds the MEMAP project with Maven

name: MEMAP build with maven

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:

  install-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout memap
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Cache Maven Packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: |
        mvn -f projects/memapOpcServer/pom.xml clean compile install -Dmaven.test.skip=true 
        mvn -f core/cim15/pom.xml clean compile install -Dmaven.test.skip=true 
        mvn -f core/powerflow/pom.xml clean compile install -Dmaven.test.skip=true
        mvn -f core/gridarchitect/pom.xml clean compile install -Dmaven.test.skip=true
        mvn -f projects/memapCore/pom.xml clean compile install -Dmaven.test.skip=true
        mvn -f projects/memapGui/pom.xml clean compile install -Dmaven.test.skip=true
