# Test: This workflow will build the MEMAP project with Maven

name: MEMAP build with maven

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  install-cim:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout memap
        uses: actions/checkout@v2
        with:
          ref: development
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache Maven Packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -f core/cim15/pom.xml clean install -Dmaven.test.skip=true -DlocalRepositoryPath=~/.m2 
      
  install-powerflow:
    needs: install-cim
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout memap
      uses: actions/checkout@v2
      with:
        ref: development
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Cache Maven Packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn -f core/powerflow/pom.xml clean install -Dmaven.test.skip=true -DlocalRepositoryPath=~/.m2   
     
  install-gridarchitect:
    needs:
      - install-cim
      - install-powerflow
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout memap
      uses: actions/checkout@v2
      with:
        ref: development
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Cache Maven Packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn -f core/gridarchitect/pom.xml clean install -Dmaven.test.skip=true -DlocalRepositoryPath=~/.m2   
      
  install-memapOpcServer:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout memap
      uses: actions/checkout@v2
      with:
        ref: development
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Cache Maven Packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn -f projects/memapOpcServer/pom.xml clean install -Dmaven.test.skip=true -DlocalRepositoryPath=~/.m2   
    
  install-memapCore:
    needs:
      - install-cim
      - install-powerflow
      - install-gridarchitect
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout memap
      uses: actions/checkout@v2
      with:
        ref: development
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Cache Maven Packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn -f projects/memapCore/pom.xml clean install -Dmaven.test.skip=true -DlocalRepositoryPath=~/.m2   
      
  install-memapGui:
    needs:
      - install-memapCore
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout memap
      uses: actions/checkout@v2
      with:
        ref: development
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Cache Maven Packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn -f projects/memapGui/pom.xml clean install -Dmaven.test.skip=true -DlocalRepositoryPath=~/.m2   
